blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/WalletConnect/walletconnect-monorepo/discussions/new?category=web3modal
    about: Ask questions and discuss with other community members.
